config/routes.rb
Futbol::Application.routes.draw do
  devise_scope :user do
    get "logout", to: "devise/sessions#destroy"
    get "login", to: "devise/sessions#new"
  end
  get "players", to: "players#index"
  get "dashboard", to: "dashboard#index"
  get "pin_player", to: "pinboard_players#new"
  devise_for :users
  resources :pinboards
  resources :pinboard_players, only: [:new, :create, :destroy]

    root 'fans#index'

  

end

app/models/pinboard.rb
# == Schema Information
#
# Table name: pinboards
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  description :text
#  player_id   :integer
#  user_id     :integer
#  created_at  :datetime
#  updated_at  :datetime
#

class Pinboard < ActiveRecord::Base
	belongs_to 	    :user
	has_many		:pinboard_players, dependent: :destroy
	has_many		:players, through: :pinboard_players

	def pin_player_to_board(player)
		PinboardPlayer.pin_player(self, player)	
	end

	
end

app/models/player.rb
# == Schema Information
#
# Table name: players
#
#  id             :integer          not null, primary key
#  first_name     :string(255)
#  last_name      :string(255)
#  jersey_number  :integer
#  height         :string(255)
#  weight         :string(255)
#  date_of_birth  :datetime
#  place_of_birth :string(255)
#  position_id    :integer
#  created_at     :datetime
#  updated_at     :datetime
#  club_id        :integer
#

class Player < ActiveRecord::Base
	require 'youtube_it'
	mount_uploader :image, ImageUploader
	belongs_to 				:position
	belongs_to 				:club
	has_many				:pinboard_players
	has_many				:pinboards, through: :pinboard_players

	# validates :first_name, :last_name, :height, :weight, :date_of_birth, :club, presence: true
	# validates :place_of_birth, presence: true, allow_blank: true
	# validates :jersey_number, numericality: { only_integer: true }


	def full_name
		"#{self.first_name}" + " " + "#{last_name}"
	end

  def player_age
    todays_date = Time.now.utc.to_date
    todays_date.year - self.date_of_birth.year
    #age = todays_date.year - self.date_of_birth.year
  end

  def self.get_videos(player)
  	vids = YouTubeIt::Client.new
  	vids.videos_by(:query => "#{player.full_name}").videos[0..4]
  end

  def get_player_news
  	#todo
  	#get news about player
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  confirmation_token     :string(255)
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  unconfirmed_email      :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#

class User < ActiveRecord::Base
	has_many :pinboards, dependent: :destroy
	has_many :pins, through: :pinboards, source: :players
	
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


      def add_player_to_pin_board(pinboard, player)
			     PinboardPlayer.pin_player(pinboard, player)
		  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
	def index
		render text: "hello world, name spaced my admin users"
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def get_player_videos(player)
  	@player_videos ||= Player.get_videos(player)
  end

  helper_method :get_player_videos
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
	before_filter :authenticate_user!
  def index
  	@current_user_pinboards = current_user.pinboards.load
  end
end

app/controllers/pinboard_players_controller.rb
class PinboardPlayersController < ApplicationController
  before_filter :authenticate_user!, only: [:create, :destroy]

  def new
     session[:player] = params[:id]
      @pinboard_player = PinboardPlayer.new(player_id: params[:id]) 
      @current_user_pinboards = get_user_pinboards
      # user_pinboards_check?
  end

  def create
    player_id = session[:player]
    @player = Player.find(player_id)
    @pinboard = current_user.pinboards.find(params[:board])
    PinboardPlayer.pin_player(@pinboard, @player)
    redirect_to pinboard_path(@pinboard)
  end
  
  def destroy
    @pinboard = params[:pinboard]
    PinboardPlayer.find_by_player_id(params[:id]).destroy
    redirect_to pinboard_path(@pinboard), notice: "Pin successfully removed"
  end

  private

  def get_user_pinboards

  	if current_user
       @current_user_pinboards = current_user.pinboards
  		 if @current_user_pinboards.empty?
          redirect_to_new_pinboard
       else
          @current_user_pinboards
       end
  	else
  		redirect_to login_path, notice: "Please sign in to pin players"
  	end
  end

  def redirect_to_new_pinboard
    redirect_to new_pinboard_path, notice: "Please create a pinboard"
  end

end

app/controllers/pinboards_controller.rb
class PinboardsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @pinboards = current_user.pinboards  
     if @pinboards.empty? 
        redirect_to new_pinboard_path, notice: "You have no pinboards"
      end
  end

  def new
  	@pinboard = Pinboard.new
    store_location
  end

  def create
  	@pinboard = current_user.pinboards.build(pinboard_params)
  	if @pinboard.save
  		flash[:notice] = "Pinboard Created"
  		redirect_to pinboards_path
  	else
  		render :new
  	end
  end
  
  def show
    @pinboard = Pinboard.find(params[:id])
    @pinboard_players = @pinboard.players
  end

  def destroy
    @pinboard = Pinboard.find(params[:id])
    @pinboard.destroy
    redirect_to dashboard_path, notice: "Pinboard #{@pinboard.name} successfully deleted"
  end

  private

  def pinboard_params
  	params.require(:pinboard).permit(:name, :description)
  end

  def store_location
      session[:return_to] = request.fullpath
   end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session[:return_to] = nil
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

  def index
  	@players = Player.all.shuffle
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper

end

app/helpers/pinboard_players_helper.rb
module PinboardPlayersHelper
	
end

app/views/dashboard/index.html.slim
.section.hero
  .w-container
    .w-row
      -if user_signed_in?
        .w-col.w-col-6.center
          = gravatar_for(current_user)
        / = image_tag "epl-banner.jpg", width: "auto", height: "auto", alt: "image-placeholder.svg", class: "hero-image"
        .w-col.w-col-6.hero-column
          h1= "Welcome #{current_user.email}"
          p Welcome to FUTOBUL, find your favorite Premier League players and GO-WILD Pinning them to you Boards.
          = link_to "Sign out", logout_path , class: "button action" 
      -else
        .w-col.w-col-6.center
          = image_tag "epl-banner.jpg", width: "auto", height: "auto", alt: "image-placeholder.svg", class: "hero-image"
        .w-col.w-col-6.hero-column
          h1 Dashboard#index
          p Welcome to FUTOBUL, find your favorite Premier League players and GO-WILD Pinning them to you Boards.
          = link_to "Sign Up", new_user_registration_path, class: "button action" 
.section
  .w-container
    .w-row
      - @current_user_pinboards.each do |pinboard|
        li= link_to "#{pinboard.name}", pinboard_path(pinboard)
        .w-col.w-col-3.w-col-small-6
          - current_user.pins.each do |pin|
           h4= pin.full_name
           - get_player_videos(pin).each do |video|
             li= link_to "Youtube Video #{pin.full_name}", video.player_url

app/views/fans/index.html.slim
.section.hero
  .w-container
    .w-row
      -if user_signed_in?
        .w-col.w-col-6.center
          = gravatar_for(current_user)
        / = image_tag "epl-banner.jpg", width: "auto", height: "auto", alt: "image-placeholder.svg", class: "hero-image"
        .w-col.w-col-6.hero-column
          h1= "Welcome #{current_user.email}"
          p Welcome to FUTOBOL, find your favorite Premier League players and GO-WILD Pinning them to you Boards.
          = link_to "Dashboard", dashboard_path , class: "button action" 
      -else
        .w-col.w-col-6.center
          = image_tag "epl-banner.jpg", width: "auto", height: "auto", alt: "image-placeholder.svg", class: "hero-image"
        .w-col.w-col-6.hero-column
          h1 Futbol Pinboard
          p Welcome to FUTOBOL, find your favorite Premier League players and GO-WILD Pinning them to you Boards.
          = link_to "Sign Up", new_user_registration_path, class: "button action" 
.section
  .w-container
    .w-row
    -if user_signed_in?
      - current_user.pins.each do |pin|
        .w-col.w-col-3.w-col-small-6
          = image_tag pin.image_url.to_s
          h4= pin.full_name
          = link_to "Delete Pin", pinboard_player_path(pin.id), method: "delete", data: { confirm: "Are you sure"}, class: "button"
    -else
        .badge
          = image_tag "world-soccer-ball-1.png", width: "auto", height: "auto"
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Futbol</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="nav-section">
	<div class="w-container">
		<div class="w-row">
			<div class="w-col w-col-4">
				<div class="company"><%= Futbol %></div>
				</div>
				<div class="w-col w-col-8 navigation-column">
				<%= link_to "Home", root_path, class: "nav-link" %>
				<%= link_to "Players", players_path, class: "nav-link" %>
				<%= link_to "Pinboards", pinboards_path, class: "nav-link" %>
				<% if user_signed_in? %>
					<%= link_to "logout", logout_path, class: "nav-link last" %>
				<% else %>
					<%= link_to "login", login_path, class: "nav-link last" %>
					<% end %>

				</div>
		</div>
	</div>
</div>
<div class="alert" >
<% if flash[:alert] %>
	<%= flash[:alert] %>
	<% end %>
	</div>
<% if flash[:notice] %>
	<div class="notice">
	<%= flash[:notice] %>
	</div>
	<% end %>
<%= yield %>
<%#= debug(params) %>

</body>
</html>

app/views/pinboard_players/_pinboard_select.html.slim
/ = @pinboard_player.inspect
.select_board
  h4 Select
  = form_for @pinboard_player do |f|
    .pinselect
      = select_tag "board", options_from_collection_for_select(@current_user_pinboards, "id", "name")
      = f.submit "Pin", class: "button"

app/views/pinboard_players/_select.html.slim
/ = @pinboard_player.inspect
.select_board
  h4 Select
  = form_for @pinboard_player do |f|
    .pinselect
      = select_tag "board", options_from_collection_for_select(@current_user_pinboards, "id", "name")
      = f.submit "Pin", class: "button"

app/views/pinboard_players/new.html.slim
.section
  / = @pinboard_player.inspect
  = form_for @pinboard_player do |f|
  	h3 Select a Pinboard
    = select_tag "board", options_from_collection_for_select(@current_user_pinboards, "id", "name")
    = f.submit "Pin Player", class: "button action"
    br= link_to "Create new board", new_pinboard_path

app/views/pinboard_players/new.js.erb
$('a.pinbutton').click(function() {
	$(this).html('<%= escape_javascript(render("pinboard_select")) %>')
});

app/views/pinboard_players/~new.html.slim
= @pinboard_player.inspect
= form_for @pinboard_player do |f|
  = select_tag "board", options_from_collection_for_select(@current_user_pinboards, "id", "name")
  = f.submit 

app/views/pinboards/_form.html.slim
.section.pinboard-form
  .header
    h1 Create New Pinboard
  = form_for @pinboard do |f|
    = f.label :name, "Pinboard Name"
    = f.text_field :name
    br= f.label :description, "Pinboard Description"
    = f.text_area :description
    = f.submit class: "button action"

app/views/pinboards/index.html.slim
.section
  .pinboards
    h1 Pinboards 
    - @pinboards.each do |board|
      h3= link_to "#{board.name} board", pinboard_path(board)
      li= board.description
      = button_to "delete Board", pinboard_path(board), method: "delete", data: { confirm: "Are you sure?"}

app/views/pinboards/show.html.slim
.content-wrapper
 .pinboard-wrapper
  h1= @pinboard.name
  
  - @pinboard_players.each do |pp|
   .player_profile
    #profile_img
      = image_tag pp.image_url.to_s
    #profile_bio
    ul
      li= pp.full_name 
      / li= pp.club.name unless pp.club.nil
      li= pp.position
      li= pp.height
      li= pp.weight
      li= pp.place_of_birth
      / li= pp.player_age
    = button_to "Remove this Pin", pinboard_player_path(pp, pinboard: @pinboard), method: "delete", data: { confirm: "Are you sure?"}

app/views/players/_player.html.slim
= content_tag "div", class: "w-col w-col-3 w-col-small-6"
  = image_tag player.image_url.to_s
  h4= player.full_name 
  = link_to "Pin", { controller: "pinboard_players", action: "new", id: player}, class: "pinbutton", id: "#{player.id}" 

app/views/players/index.html.slim
.section
  .w-container
    .w-row
      - @players.each do |player|
        = render "player", player: player
        